# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8a312c975e1dd81bbce6c6429349ef8c119e16dd3d80c1d5ecdd372c6bffab152867ed0d26a7c71ffd337a7efc0e4a53e81ad355c47a98b21b783481e5fa68a

test:
  secret_key_base: b31a9e48e1df30c3acb2fcd851feb624cf68f5ba326477e7a69b03f5643f86baccb8b5b8ecfb820acaf7c53d7db2c551e8d522b8450ffc1b8c39fc4b95d0053e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
